// =============================================================================
// Generated by efx_ipmgr
// Version: 2025.1.110.5.9
// IP Version: 6.2
// =============================================================================

////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2013-2025 Efinix Inc. All rights reserved.              
//
// This   document  contains  proprietary information  which   is        
// protected by  copyright. All rights  are reserved.  This notice       
// refers to original work by Efinix, Inc. which may be derivitive       
// of other work distributed under license of the authors.  In the       
// case of derivative work, nothing in this notice overrides the         
// original author's license agreement.  Where applicable, the           
// original license agreement is included in it's original               
// unmodified form immediately below this header.                        
//                                                                       
// WARRANTY DISCLAIMER.                                                  
//     THE  DESIGN, CODE, OR INFORMATION ARE PROVIDED “AS IS” AND        
//     EFINIX MAKES NO WARRANTIES, EXPRESS OR IMPLIED WITH               
//     RESPECT THERETO, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES,  
//     INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF          
//     MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR    
//     PURPOSE.  SOME STATES DO NOT ALLOW EXCLUSIONS OF AN IMPLIED       
//     WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO LICENSEE.           
//                                                                       
// LIMITATION OF LIABILITY.                                              
//     NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR BODILY       
//     INJURY, EFINIX SHALL NOT BE LIABLE WITH RESPECT TO ANY SUBJECT    
//     MATTER OF THIS AGREEMENT UNDER TORT, CONTRACT, STRICT LIABILITY   
//     OR ANY OTHER LEGAL OR EQUITABLE THEORY (I) FOR ANY INDIRECT,      
//     SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY    
//     CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF      
//     GOODWILL, DATA OR PROFIT, WORK STOPPAGE, OR COMPUTER FAILURE OR   
//     MALFUNCTION, OR IN ANY EVENT (II) FOR ANY AMOUNT IN EXCESS, IN    
//     THE AGGREGATE, OF THE FEE PAID BY LICENSEE TO EFINIX HEREUNDER    
//     (OR, IF THE FEE HAS BEEN WAIVED, $100), EVEN IF EFINIX SHALL HAVE 
//     BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO 
//     NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR            
//     CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT   
//     APPLY TO LICENSEE.                                                
//
////////////////////////////////////////////////////////////////////////////////

localparam ADDR_WIDTH_A = 10;
localparam ADDR_WIDTH_B = 10;
localparam RESET_A_ENABLE = 0;
localparam RESET_B_ENABLE = 0;
localparam RSTA_POLARITY = 1;
localparam RSTB_POLARITY = 1;
localparam FAMILY = "TITANIUM";
localparam MEMORY_MODE = "SPEED";
localparam WRITE_MODE_A = "READ_FIRST";
localparam WRITE_MODE_B = "READ_FIRST";
localparam OUTPUT_REG_A = 0;
localparam OUTPUT_REG_B = 0;
localparam MEMORY_TYPE = "TDP_RAM";
localparam GROUP_DATA_WIDTH_B = 90;
localparam BYTEENA_ENABLE = 0;
localparam BYTEENB_ENABLE = 0;
localparam BYTEENA_POLARITY = 1;
localparam BYTEENB_POLARITY = 1;
localparam BYTEEN_WIDTH_A = 1;
localparam BYTEEN_WIDTH_B = 1;
localparam BYTEEN_ENABLE = 0;
localparam BYTEEN_POLARITY = 1;
localparam GROUP_DATA_WIDTH = 90;
localparam BYTEEN_WIDTH = 1;
localparam WIDTH_RATIO = 4;
localparam GROUP_DATA_WIDTH_A = 90;
localparam DATA_WIDTH_A = 90;
localparam DATA_WIDTH_B = 90;
localparam ADDREN_ENABLE = 1;
localparam ADDREN_POLARITY = 1;
localparam CLK_MODE = 1;
localparam CLKA_POLARITY = 1;
localparam CLKB_POLARITY = 1;
localparam CLKE_POLARITY = 1;
localparam CLKEA_POLARITY = 1;
localparam CLKEA_ENABLE = 0;
localparam RESET_OUTREG_A = "ASYNC";
localparam RESET_OUTREG_B = "ASYNC";
localparam RESET_RAM_B = "ASYNC";
localparam WEA_ENABLE = 1;
localparam WEA_POLARITY = 1;
localparam WEB_ENABLE = 1;
localparam WEB_POLARITY = 1;
localparam RADDREN_ENABLE = 1;
localparam RADDREN_POLARITY = 1;
localparam WADDREN_ENABLE = 1;
localparam WADDREN_POLARITY = 1;
localparam RCLK_POLARITY = 1;
localparam ADDREN_A_ENABLE = 0;
localparam ADDREN_B_ENABLE = 0;
localparam ADDRENA_POLARITY = 1;
localparam ADDRENB_POLARITY = 1;
localparam WE_ENABLE = 1;
localparam WE_POLARITY = 1;
localparam WCLKE_ENABLE = 0;
localparam WCLKE_POLARITY = 1;
localparam WCLK_POLARITY = 1;
localparam RESET_RAM_A = "ASYNC";
localparam RESET_RAM = "ASYNC";
localparam CLK_POLARITY = 1;
localparam OUTPUT_REG = 0;
localparam RE_POLARITY = 1;
localparam RE_ENABLE = 1;
localparam WRITE_MODE = "READ_FIRST";
localparam RESET_OUTREG = "ASYNC";
localparam RESET_ENABLE = 1;
localparam RST_POLARITY = 1;
localparam CLKEB_POLARITY = 1;
localparam CLKEB_ENABLE = 0;
